name = "waitwhat"
compatibility_date = "2026-01-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".output/public"

[assets]
directory = "dist"
not_found_handling = "single-page-application"
